services:
  backend:
    container_name: backend-1
    build: ./example-backend
    command: ./server
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
  frontend:
    container_name: frontend-1
    build: ./example-frontend
    command: serve -s -l 5000 build
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  redis:
    image: "redis:alpine"
