services:

  backend:
    container_name: backend-cont
    build: ./example-backend
    command: ./server
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=our-database

  frontend:
    container_name: frontend-cont
    build: ./example-frontend
    command: serve -s -l 5000 build
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  redis:
    image: "redis:alpine"

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=our-database
    container_name: postgres-db
    volumes:
      - ./data:/var/lib/postgresql/data
